const routes = {
  home: "/",
  login: "login",
  register: "register",
  forgotpw: "forgotpw",
  team: "team",
  about: "about",
  testimonials: "testimonials",
  history: "history",
  products: "products",
  contact: "contact",

  dashboard: "dashboard",
  product: "productdetails",
  features: "featuresection",
  notifi: "notifications",
  profile: "profile",
  profileedit: "profileedit",
  settings: "usersettings",
  changepw: "changepw",
  upload: "upload",
  download: "download",
  maintenance: "maintenance",
};
export { routes as routesConfig };
